epochs: 50                  # Number of training epochs
batch_size: 12              # Size of each batch
lr: 0.001                   # Learning rate for the optimizer
cfg_src: 8.0                # Path or identifier for the source configuration or model
eta: 1                    # Parameter for the noise schedule or other diffusion process
cfg_scale_tar_list:         # List of target configuration scales
  - 7.0
  - 8.0
  - 10.0
num_diffusion_steps: 20   # Number of diffusion steps in the model
